### ISSUE TITLE
[Bug] Main widget is called before the end of `onUserFirstJoin`

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/application-runner#178]
It seems that we do not wait for the end of the async listener `onUserFirstJoin` before showing the UI. This means that if you put some changes in the `_users` datastore and if the main widget needs access to the `_users` datastore, the widget will not see the changes.

Before, we could just refresh the page, this would reload the main widget which would properly get the `_users` datastore data.
But now, even if we refresh the page, the error still occurs.

## How to reproduce 

Clone https://github.com/jonas-martinez/achiever and run with the changes in this PR : https://github.com/lenra-io/dev-tools/pull/130

It seems to be a problem coming from updating application-runner from beta-36 to beta-44

**Comment by taorepoara** [comment]
@pichoemr Is it fixed ?

**Comment by Nesqwik** [comment]
This should have been be fixed in the mongo update !
