### ISSUE TITLE
[Bug]: Create and update doc do not return the doc

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/application-runner#251]
### What happened?

Tried to create a doc in my app and use the created doc id in another one but the response data is empty.

The [create](https://github.com/lenra-io/application-runner/blob/c7921768099461eea7519587800eaa152ccb77b1/lib/controllers/docs_controller.ex#L68) and [update](https://github.com/lenra-io/application-runner/blob/c7921768099461eea7519587800eaa152ccb77b1/lib/controllers/docs_controller.ex#L86) functions should return the doc to let the apps use it directly.

### Version

v1.0.0-beta.68 of application-runner

**Comment by jonas-martinez** [comment]
@pichoemr Can you take a look at this ?
