### ISSUE TITLE
[Task] Mongo transaction route rework

### ISSUE THREAD

**Issue by pichoemr** [lenra-io/application-runner#305]
## What should be done 
We need to avoid having two different routes for the data route (with and without transaction).
For this we can remove the on verify in AppGuardian, and remove the token from the env/session metadata.
Add two resource_from_claims, one with {env_id, transaction_id} and one with {user_id, env_id, transaction_id}, if transaction_id present add the action to the transaction.
We need to create a new token for each listener.
We need to create a token with transaction_id and return it on the start_transaction request.

**Comment by taorepoara** [comment]
@pichoemr Is it resovled by the new route system ?

**Comment by pichoemr** [comment]
No, we need to do the work
