### ISSUE TITLE
I don't think that there is seeds in this project

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/application-runner#345]
I don't think that there is seeds in this project

_Originally posted by @taorepoara in https://github.com/lenra-io/application-runner/pull/340#discussion_r1198997145_

**Comment by jonas-martinez** [comment]
What do you mean by this issue ? Can you add more context to it and explain why seeds would be needed ?

**Comment by taorepoara** [comment]
It use to have the use of seeds in this project in mix setup, but it does not exist.

It seems that it's been resolved
